# use this file to configure anything related to immich.
# docker-compose.yml is pure immich compose file grabbed from github releases

services:
  immich-server:
    hostname: immich
    profiles:
      - default
    networks:
      tailscale-docker-net:
        ipv4_address: "${IMMICH_IP?:error}"
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding

    environment:

      # disabled
      - IMMICH_MACHINE_LEARNING_URL=false
      - IMMICH_MACHINE_LEARNING_ENABLED=false
      # - IMMICH_LOG_LEVEL=verbose

      # The values below this line do not need to be changed
      ###################################################################################
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich

      - REDIS_HOSTNAME=immich_redis

  immich-machine-learning:
    profiles:
      - ml
    # networks:
    #   tailscale-docker-net:
    #     ipv4_address: "${IMMICH_ML_IP?:error}"
    deploy:
      replicas: 0

  redis:
    hostname: immich_redis
    profiles:
      - default
    networks:
      tailscale-docker-net:
        ipv4_address: "${IMMICH_REDIS_IP?:error}"

  database:
    hostname: immich_postgres
    profiles:
      - default
    networks:
      tailscale-docker-net:
        ipv4_address: "${IMMICH_POSTGRES_IP?:error}"

    environment:
      # this is all hardcoded and public as this only lives inside docker network.
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'immich'
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'

networks:
  tailscale-docker-net:
    name: "${DOCKER_NETWORK}"
    external: true